# -*- coding: utf-8 -*-
"""project108.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10DE3oniBCf4Ua0jzMOmxtyEIdSGD80Xp
"""

from google.colab import files
data_to_load=files.upload()

import pandas as pd
import plotly.figure_factory as ff
import csv

df = pd.read_csv("data.csv")
fig = ff.create_distplot([df["Mobile Brand"].tolist()],["Avg Rating"],show_hist=False)
fig.show()

